# Generated by Django 2.0.6 on 2018-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
